### PR TITLE
fix: Fix panic when resyncing after consensus database is deleted

### LINKED ISSUE #204: Chain sync crash
### Current Behavior

```
2024-12-13T05:26:32-05:00	INFO	node started	{"syncer": "[::]:9981", "http": "127.0.0.1:9980", "version": "v0.8.0", "commit": "e549203"}
2024-12-13T05:26:32-05:00	PANIC	wallet.sync	failed to sync store	{"error": "failed to subscribe to chain manager: missing block at index 490977::f9b2ba46"}
panic: failed to sync store

goroutine 55 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc00038e080?})
	go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0003b01a0, {0xc0003ac040, 0x1, 0x1})
	go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
go.uber.org/zap.(*Logger).Panic(0x1bcb0c0?, {0xb32c43?, 0x1bcb060?}, {0xc0003ac040, 0x1, 0x1})
	go.uber.org/zap@v1.27.0/logger.go:285 +0x51
go.sia.tech/walletd/wallet.NewManager.func2()
	go.sia.tech/walletd/wallet/manager.go:386 +0x653
created by go.sia.tech/walletd/wallet.NewManager in goroutine 1
	go.sia.tech/walletd/wallet/manager.go:363 +0x399
```

So far I have found it is likely in the sqlite db itself, which is problematic as I cant just delete that without re-importing all accounts. Deleting the consensus db helps none.

### Expected Behavior

Walletd to boot normally with my data

### Steps to Reproduce

_No response_

### Version

v0.12.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Linux Mint

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by n8maninger**
Fixes a panic that occurs when the consensus database is deleted and the node is attempting to sync. This will remove all existing consensus state from the database and rescan from genesis without affecting the wallet data.

Fixes #204

### CODE REVIEW

File: wallet/manager.go [hunk 1]
```diff
@@ -380,7 +382,12 @@ func NewManager(cm ChainManager, store Store, opts ...Option) (*Manager, error)
 			m.mu.Lock()
 			// update the store
 			lastTip, err := store.LastCommittedIndex()
-			if err != nil {
+			if err != nil && strings.Contains(err.Error(), "missing block at index") {
```
Comment (ChrisSchinnerl) [inline wallet/manager.go:385]: (nit) expose an error that you can check for rather than checking a string

File: wallet/wallet_test.go [hunk 2]
```diff
@@ -3512,3 +3513,115 @@ func TestEventTypes(t *testing.T) {
...
+	for i := 0; i < 50; i++ {
+		mineBlock(1, frand.Entropy256())
+	}
+
+	assertBalance(t, addr, genesisState.BlockReward(), genesisState.SiafundCount())
+
+	// close the wallet and reset it
+	if err := wm.Close(); err != nil {
+		t.Fatal(err)
+	} else if err := db.ResetChainState(); err != nil {
```
Comment (ChrisSchinnerl) [inline wallet/wallet_test.go:3594]: Depending on how annoying it is to do my preference would be to make sure `NewManager` calls `ResetChainState` itself to also get that part into the test rather than manually resetting it.

**Review by peterjan — APPROVED** [review]
nothing to add to Chris's remarks 👍 LGTM

File: wallet/manager.go (hunk 1 above)
Comment (n8maninger) [reply wallet/manager.go]: Needs to happen in `coreutils`

**Review by ChrisSchinnerl — APPROVED** [review]
Lgtm. Successfully verified on Zen.
