### PR TITLE
Fix foreign key failure when deleting a wallet

### LINKED ISSUE #85: Cant delete wallet without first deleting all addresses
Attempting to delete a wallet with addresses results in:
> couldn't remove wallet: transaction failed (attempt 1): FOREIGN KEY constraint failed

I was expecting the endpoint to delete the wallet and all related data.

### PR DESCRIPTION
**Pull request by n8maninger**
Fixes #85

### CODE REVIEW

File: persist/sqlite/wallet.go [hunk 1]
```diff
@@ -175,8 +175,13 @@ func (s *Store) UpdateWallet(w wallet.Wallet) (wallet.Wallet, error) {
 // addresses that were previously associated with the wallet.
 func (s *Store) DeleteWallet(id wallet.ID) error {
 	return s.transaction(func(tx *txn) error {
+		_, err := tx.Exec(`DELETE FROM wallet_addresses WHERE wallet_id=$1`, id)
```
Comment (ChrisSchinnerl) [inline persist/sqlite/wallet.go:178]: Is there ever a reason for us to be able to delete a wallet without deleting the wallet addresses? If not a CASCADE would probably also do the trick.

**Review by ChrisSchinnerl — APPROVED** [review]
